#define PLAYER_TEXTURE_NAME "Player"
#define PLAYER_TEXTURE_FILE_NAME "resources/img/player.png"
#define WEAPON_TEXTURE_NAME "Weapon"
#define WEAPON_TEXTURE_FILE_NAME "resources/img/sword.png"
#define BACKGROUND_THEME_NAME "BackgroundTheme"
#define BACKGROUND_THEME_FILE_NAME "resources/audio/background_theme.wav"